---
name: tests

on:
  pull_request:
  push:
    branches:
      - main

env:
  VCC_USER: ${{ secrets.VCC_USER }}
  VCC_PASS: ${{ secrets.VCC_PASS }}
  GOPROXY: direct 

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.3

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Golang Tests
      run: go test -v ./...

    - name: Setup BATS
      if: runner.os != 'windows'
      run: |
        set -e

        if [ -n "$GITHUB_RUN_ID" ]; then
            export GITHUB_API_TOKEN="${{ secrets.GITHUB_TOKEN }}"
        fi

        git clone https://github.com/bats-core/bats-core.git && bats-core/install.sh $HOME

    - name: Run BATS Tests
      if: runner.os != 'windows'
      run: |
        export PATH=${PATH}:/home/runner/bin
        # Retry hack to attempt test 3 times
        bats test/bats
